// AniList Filter Constants

export const GENRES = [
  'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Ecchi',
  'Fantasy',
  'Horror',
  'Mahou Shoujo',
  'Mecha',
  'Music',
  'Mystery',
  'Psychological',
  'Romance',
  'Sci-Fi',
  'Slice of Life',
  'Sports',
  'Supernatural',
  'Thriller',
] as const;

export const TAGS = [
  '4-koma',
  'Achromatic',
  'Achronological Order',
  'Acrobatics',
  'Acting',
  'Adoption',
  'Advertisement',
  'Afterlife',
  'Age Gap',
  'Age Regression',
  'Agender',
  'Agriculture',
  'Airsoft',
  'Alchemy',
  'Aliens',
  'Alternate Universe',
  'American Football',
  'Amnesia',
  'Anachronism',
  'Ancient China',
  'Angels',
  'Animals',
  'Anthology',
  'Anthropomorphism',
  'Anti-Hero',
  'Archery',
  'Aromantic',
  'Arranged Marriage',
  'Artificial Intelligence',
  'Asexual',
  'Assassins',
  'Astronomy',
  'Athletics',
  'Augmented Reality',
  'Autobiographical',
  'Aviation',
  'Badminton',
  'Ballet',
  'Band',
  'Bar',
  'Baseball',
  'Basketball',
  'Battle Royale',
  'Biographical',
  'Bisexual',
  'Blackmail',
  'Board Game',
  'Boarding School',
  'Body Horror',
  'Body Image',
  'Body Swapping',
  'Bowling',
  'Boxing',
  "Boys' Love",
  'Bullying',
  'Butler',
  'Calligraphy',
  'Camping',
  'Cannibalism',
  'Card Battle',
  'Cars',
  'Centaur',
  'CGI',
  'Cheerleading',
  'Chibi',
  'Chimera',
  'Chuunibyou',
  'Circus',
  'Class Struggle',
  'Classic Literature',
  'Classical Music',
  'Clone',
  'Coastal',
  'Cohabitation',
  'College',
  'Coming of Age',
  'Conspiracy',
  'Cosmic Horror',
  'Cosplay',
  'Cowboys',
  'Creature Taming',
  'Crime',
  'Criminal Organization',
  'Crossdressing',
  'Crossover',
  'Cult',
  'Cultivation',
  'Curses',
  'Cute Boys Doing Cute Things',
  'Cute Girls Doing Cute Things',
  'Cyberpunk',
  'Cyborg',
  'Cycling',
  'Dancing',
  'Death Game',
  'Delinquents',
  'Demons',
  'Denpa',
  'Desert',
  'Detective',
  'Dinosaurs',
  'Disability',
  'Dissociative Identities',
  'Dragons',
  'Drawing',
  'Drugs',
  'Dullahan',
  'Dungeon',
  'Dystopian',
  'E-Sports',
  'Eco-Horror',
  'Economics',
  'Educational',
  'Elderly Protagonist',
  'Elf',
  'Ensemble Cast',
  'Environmental',
  'Episodic',
  'Ero Guro',
  'Espionage',
  'Estranged Family',
  'Exorcism',
  'Fairy',
  'Fairy Tale',
  'Fake Relationship',
  'Family Life',
  'Fashion',
  'Female Harem',
  'Female Protagonist',
  'Femboy',
  'Fencing',
  'Filmmaking',
  'Firefighters',
  'Fishing',
  'Fitness',
  'Flash',
  'Food',
  'Football',
  'Foreign',
  'Found Family',
  'Fugitive',
  'Full CGI',
  'Full Color',
  'Gambling',
  'Gangs',
  'Gender Bending',
  'Ghost',
  'Go',
  'Goblin',
  'Gods',
  'Golf',
  'Gore',
  'Guns',
  'Gyaru',
  'Handball',
  'Henshin',
  'Heterosexual',
  'Hikikomori',
  'Hip-hop Music',
  'Historical',
  'Homeless',
  'Horticulture',
  'Ice Skating',
  'Idol',
  'Indigenous Cultures',
  'Inn',
  'Isekai',
  'Iyashikei',
  'Jazz Music',
  'Josei',
  'Judo',
  'Kabuki',
  'Kaiju',
  'Karuta',
  'Kemonomimi',
  'Kids',
  'Kingdom Management',
  'Konbini',
  'Kuudere',
  'Lacrosse',
  'Language Barrier',
  'LGBTQ+ Themes',
  'Long Strip',
  'Lost Civilization',
  'Love Triangle',
  'Mafia',
  'Magic',
  'Mahjong',
  'Maids',
  'Makeup',
  'Male Harem',
  'Male Protagonist',
  'Manzai',
  'Marriage',
  'Martial Arts',
  'Matchmaking',
  'Matriarchy',
  'Medicine',
  'Medieval',
  'Memory Manipulation',
  'Mermaid',
  'Meta',
  'Metal Music',
  'Military',
  'Mixed Gender Harem',
  'Mixed Media',
  'Modeling',
  'Monster Boy',
  'Monster Girl',
  'Mopeds',
  'Motorcycles',
  'Mountaineering',
  'Musical Theater',
  'Mythology',
  'Natural Disaster',
  'Necromancy',
  'Nekomimi',
  'Ninja',
  'No Dialogue',
  'Noir',
  'Non-fiction',
  'Nudity',
  'Nun',
  'Office',
  'Office Lady',
  'Oiran',
  'Ojou-sama',
  'Orphan',
  'Otaku Culture',
  'Outdoor Activities',
  'Pandemic',
  'Parenthood',
  'Parkour',
  'Parody',
  'Philosophy',
  'Photography',
  'Pirates',
  'Poker',
  'Police',
  'Politics',
  'Polyamorous',
  'Post-Apocalyptic',
  'POV',
  'Pregnancy',
  'Primarily Adult Cast',
  'Primarily Animal Cast',
  'Primarily Child Cast',
  'Primarily Female Cast',
  'Primarily Male Cast',
  'Primarily Teen Cast',
  'Prison',
  'Proxy Battle',
  'Psychosexual',
  'Puppetry',
  'Rakugo',
  'Real Robot',
  'Rehabilitation',
  'Reincarnation',
  'Religion',
  'Rescue',
  'Restaurant',
  'Revenge',
  'Reverse Isekai',
  'Robots',
  'Rock Music',
  'Rotoscoping',
  'Royal Affairs',
  'Rugby',
  'Rural',
  'Samurai',
  'Satire',
  'School',
  'School Club',
  'Scuba Diving',
  'Seinen',
  'Shapeshifting',
  'Ships',
  'Shogi',
  'Shoujo',
  'Shounen',
  'Shrine Maiden',
  'Skateboarding',
  'Skeleton',
  'Slapstick',
  'Slavery',
  'Snowscape',
  'Software Development',
  'Space',
  'Space Opera',
  'Spearplay',
  'Steampunk',
  'Stop Motion',
  'Succubus',
  'Suicide',
  'Sumo',
  'Super Power',
  'Super Robot',
  'Superhero',
  'Surfing',
  'Surreal Comedy',
  'Survival',
  'Swimming',
  'Swordplay',
  'Table Tennis',
  'Tanks',
  'Tanned Skin',
  'Teacher',
  "Teens' Love",
  'Tennis',
  'Terrorism',
  'Time Loop',
  'Time Manipulation',
  'Time Skip',
  'Tokusatsu',
  'Tomboy',
  'Torture',
  'Tragedy',
  'Trains',
  'Transgender',
  'Travel',
  'Triads',
  'Tsundere',
  'Twins',
  'Unrequited Love',
  'Urban',
  'Urban Fantasy',
  'Vampire',
  'Vertical Video',
  'Veterinarian',
  'Video Games',
  'Vikings',
  'Villainess',
  'Virtual World',
  'Vocal Synth',
  'Volleyball',
  'VTuber',
  'War',
  'Werewolf',
  'Wilderness',
  'Witch',
  'Work',
  'Wrestling',
  'Writing',
  'Wuxia',
  'Yakuza',
  'Yandere',
  'Youkai',
  'Yuri',
  'Zombie',
] as const;

export const SEASONS = ['WINTER', 'SPRING', 'SUMMER', 'FALL'] as const;

export const FORMATS = [
  { value: 'TV', label: 'TV Show' },
  { value: 'MOVIE', label: 'Movie' },
  { value: 'TV_SHORT', label: 'TV Short' },
  { value: 'SPECIAL', label: 'Special' },
  { value: 'OVA', label: 'OVA' },
  { value: 'ONA', label: 'ONA' },
  { value: 'MUSIC', label: 'Music' },
] as const;

export const STATUSES = [
  { value: 'RELEASING', label: 'Airing' },
  { value: 'FINISHED', label: 'Finished' },
  { value: 'NOT_YET_RELEASED', label: 'Not Yet Aired' },
  { value: 'CANCELLED', label: 'Cancelled' },
] as const;

export const SORT_OPTIONS = [
  { value: 'TITLE_ROMAJI', label: 'Title' },
  { value: 'POPULARITY_DESC', label: 'Popularity' },
  { value: 'SCORE_DESC', label: 'Average Score' },
  { value: 'TRENDING_DESC', label: 'Trending' },
  { value: 'FAVOURITES_DESC', label: 'Favorites' },
  { value: 'ID_DESC', label: 'Date Added' },
  { value: 'START_DATE_DESC', label: 'Release Date' },
  { value: 'START_DATE', label: 'Release Date (Oldest)' },
] as const;

// Generate years from 1940 to next year
const currentYear = new Date().getFullYear();
export const YEARS = Array.from({ length: currentYear - 1940 + 2 }, (_, i) => currentYear + 1 - i);

// Tag categories for better organization
export const TAG_CATEGORIES: Record<string, string[]> = {
  'Theme': [
    'Isekai', 'Reincarnation', 'Revenge', 'Survival', 'Time Loop', 'Time Manipulation',
    'Coming of Age', 'Tragedy', 'Conspiracy', 'War', 'Politics', 'Crime', 'Mystery',
    'Afterlife', 'Post-Apocalyptic', 'Dystopian', 'Apocalypse',
  ],
  'Setting': [
    'School', 'College', 'Military', 'Historical', 'Medieval', 'Space', 'Urban', 'Rural',
    'Cyberpunk', 'Steampunk', 'Virtual World', 'Dungeon', 'Prison', 'Office',
  ],
  'Cast': [
    'Male Protagonist', 'Female Protagonist', 'Ensemble Cast', 'Anti-Hero',
    'Primarily Male Cast', 'Primarily Female Cast', 'Primarily Teen Cast',
  ],
  'Romance': [
    'Romance', 'Love Triangle', 'Arranged Marriage', 'Fake Relationship', 'Harem',
    "Boys' Love", 'Yuri', 'Heterosexual', 'LGBTQ+ Themes',
  ],
  'Supernatural': [
    'Magic', 'Super Power', 'Demons', 'Angels', 'Vampire', 'Werewolf', 'Ghost', 'Zombie',
    'Dragons', 'Gods', 'Youkai', 'Witch', 'Alchemy', 'Necromancy', 'Exorcism',
  ],
  'Sports': [
    'Basketball', 'Baseball', 'Football', 'Soccer', 'Tennis', 'Swimming', 'Boxing',
    'Martial Arts', 'E-Sports', 'Volleyball', 'Golf', 'Cycling',
  ],
  'Style': [
    'CGI', 'Chibi', 'Full Color', 'Rotoscoping', 'Stop Motion',
  ],
};

export type Genre = typeof GENRES[number];
export type Tag = typeof TAGS[number];
export type Season = typeof SEASONS[number];
